### ISSUE TITLE
你执行npm run docs:dev的时候访问浏览器有报错么

### ISSUE THREAD

**Issue by gengchen528** [vxhly/vtp-component#1]
![image](https://user-images.githubusercontent.com/20028566/63843609-36fa0b00-c9b9-11e9-81d6-2166a2a4fbed.png)

**Comment by vxhly** [comment]
这位小主,请使用全局 的 vuepress 来运行项目,,如果在 `package.json` 中添加过 `vuepress` 请删除哦

**Comment by gengchen528** [comment]
> 这位小主,请使用全局 的 vuepress 来运行项目,,如果在 `package.json` 中添加过 `vuepress` 请删除哦

可以了，不过为什么必须用全局执行才可以呢，可以请教一下么

**Comment by vxhly** [comment]
局部的 vuepress 可能无法识别默认的布局文件
